swagger: '2.0'
info:
  version: ''
  title: Support
  description: |
    ## Welcome

    This is a place to put general notes and extra information, for internal use.

    To get started designing/documenting this API, select a version on the left. # Title
    No Description
securityDefinitions:
  oauth2:
    type: oauth2
    flow: accessCode
    scopes: {}
    authorizationUrl: ''
    tokenUrl: ''
paths:
  /tickets:
    get:
      operationId: GET_tickets
      tags:
        - Tickets
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/trait:apiVersionHeader:Zendesk-API-Version'
        - $ref: '#/parameters/trait:requestPriorityHeader:Zendesk-Request-Priority'
        - $ref: '#/parameters/trait:cursorPagination:start_after'
        - $ref: '#/parameters/trait:cursorPagination:end_before'
        - $ref: '#/parameters/trait:cursorPagination:limit'
        - $ref: '#/parameters/trait:includeParameter:include'
        - $ref: '#/parameters/trait:ticketAssociations:organization'
        - $ref: '#/parameters/trait:ticketAssociations:requester'
        - $ref: '#/parameters/trait:ticketAssociations:collaborator'
        - $ref: '#/parameters/trait:ticketAssociations:assignee'
        - $ref: '#/parameters/trait:ticketAssociations:group'
        - $ref: '#/parameters/trait:ticketAssociations:external_id'
        - $ref: '#/parameters/trait:ticketSorting:sort_by'
        - $ref: '#/parameters/trait:ticketSorting:sort_order'
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              ticket:
                $ref: '#/definitions/ticket'
    post:
      operationId: POST_tickets
      tags:
        - Tickets
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/ticket'
        - $ref: '#/parameters/trait:apiVersionHeader:Zendesk-API-Version'
        - $ref: '#/parameters/trait:requestPriorityHeader:Zendesk-Request-Priority'
        - $ref: '#/parameters/trait:includeParameter:include'
      responses:
        default:
          description: ''
          schema: {}
  '/tickets/{id}':
    parameters:
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: GET_tickets-id
      tags:
        - Tickets
      produces:
        - application/json
      parameters:
        - name: include
          in: query
          type: array
        - name: ''
          in: query
          type: string
        - name: Zendesk-API-Version
          in: header
          type: string
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              ticket:
                $ref: '#/definitions/ticket'
              links:
                type: object
                properties:
                  self:
                    type: string
          examples:
            application/json:
              ticket:
                id: '1'
                external_id: '123'
                brand_id: '934897'
                form_id: '8437'
                channel:
                  id: twitter
                  name: ''
                people:
                  requester:
                    id: '5031726587'
                    name: Jennifer Hansen
                    email: jennifer@example.com
                  submitter_id: '5031726587'
                  assignee_id: '5031726587'
                  group_id: '28223607'
                  collaborators:
                    '456789': true
                sharing_agreements:
                  '53258401': true
                fields:
                  tags:
                    sample: true
                    zendesk: true
                  ticket_type: incident
                  subject:
                    text: 'Sample ticket: Meet the ticket'
                  priority: normal
                  status: open
                  custom:
                    custom_field_key:
                      value: ''
                      type: ''
                      name: ''
                metrics:
                  group_stations: 7
                  assignee_stations: 1
                  reopens: 55
                  replies: 322
                  reply_time_in_minutes:
                    calendar: 2391
                    business: 737
                  first_resolution_time:
                    calendar: 2391
                    business: 737
                  full_resolution_time:
                    calendar: 2391
                    business: 737
                  agent_wait_time:
                    calendar: 2391
                    business: 737
                  requester_wait_time:
                    calendar: 2391
                    business: 737
                  on_hold_time:
                    calendar: 2290
                    business: 637
                dates:
                  created: '2016-03-03T05:16:34Z'
                  updated: '2016-03-21T22:54:55Z'
                  assignee_updated: '2011-05-06T10:38:52Z'
                  requester_updated: '2011-05-07T10:38:52Z'
                  status_updated: '2011-05-04T10:38:52Z'
                  initially_assigned: '2011-05-03T10:38:52Z'
                  assigned: '2011-05-05T10:38:52Z'
                  solved: '2011-05-09T10:38:52Z'
                  latest_comment: '2011-05-09T10:38:52Z'
                audits:
                  - null
              links:
                self: 'https://z3napi.zendesk.com/api/support/tickets/1'
    patch:
      operationId: PATCH_tickets-id
      tags:
        - Tickets
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/ticket'
        - $ref: '#/parameters/trait:apiVersionHeader:Zendesk-API-Version'
        - $ref: '#/parameters/trait:requestPriorityHeader:Zendesk-Request-Priority'
        - $ref: '#/parameters/trait:cursorPagination:start_after'
        - $ref: '#/parameters/trait:cursorPagination:end_before'
        - $ref: '#/parameters/trait:cursorPagination:limit'
        - $ref: '#/parameters/trait:includeParameter:include'
      responses:
        default:
          description: ''
          schema: {}
    delete:
      operationId: DELETE_tickets-id
      tags:
        - Tickets
      parameters:
        - $ref: '#/parameters/trait:apiVersionHeader:Zendesk-API-Version'
        - $ref: '#/parameters/trait:requestPriorityHeader:Zendesk-Request-Priority'
      responses:
        default:
          description: ''
          schema: {}
  /ticket_audits:
    get:
      operationId: GET_ticket_audits
      summary: List Ticket Audits
      tags:
        - Ticket Audits
      description: |-
        Fetch audits from all tickets, in descending chronological order. Cursor-based pagination using the audit_id.
        Does not return audits from archived tickets.
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/trait:cursorPagination:start_after'
        - $ref: '#/parameters/trait:cursorPagination:end_before'
        - $ref: '#/parameters/trait:cursorPagination:limit'
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              audits:
                type: array
                items:
                  type: object
                  properties:
                    created_at:
                      type: string
                    via:
                      type: object
                      properties:
                        channel:
                          type: string
                    metadata:
                      type: object
                      properties:
                        system:
                          type: object
                          properties:
                            location:
                              type: string
                            client:
                              type: string
                            ip_address:
                              type: string
                        custom:
                          type: object
                    id:
                      type: string
                    ticket_id:
                      type: integer
                    events:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          type:
                            type: string
                          via:
                            type: object
                            properties:
                              channel:
                                type: string
                              source:
                                type: object
                                properties:
                                  to:
                                    type: object
                                  from:
                                    type: object
                                    properties:
                                      id:
                                        type: integer
                                      title:
                                        type: string
                                  rel:
                                    type: string
                          comment:
                            type: object
                            properties:
                              body:
                                type: object
                                properties:
                                  text:
                                    type: string
                                  html:
                                    type: string
                                  '':
                                    type: string
                              public:
                                type: boolean
                              id:
                                type: string
                              attachments:
                                type: array
                                items:
                                  type: object
                              author_id:
                                type: string
                          field:
                            type: object
                            properties:
                              value:
                                type: string
                              previous_value:
                                type: string
                              id:
                                type: string
parameters:
  'trait:cursorPagination:start_after':
    name: start_after
    in: query
    type: string
  'trait:cursorPagination:end_before':
    name: end_before
    in: query
    type: string
  'trait:cursorPagination:limit':
    name: limit
    in: query
    type: string
  'trait:ticketAssociations:organization':
    name: organization
    in: query
    type: string
  'trait:ticketAssociations:requester':
    name: requester
    in: query
    type: string
  'trait:ticketAssociations:collaborator':
    name: collaborator
    in: query
    type: string
  'trait:ticketAssociations:assignee':
    name: assignee
    in: query
    type: string
  'trait:ticketAssociations:group':
    name: group
    in: query
    type: string
  'trait:ticketAssociations:external_id':
    name: external_id
    in: query
    type: string
  'trait:apiVersionHeader:Zendesk-API-Version':
    name: Zendesk-API-Version
    in: header
    type: string
  'trait:requestPriorityHeader:Zendesk-Request-Priority':
    name: Zendesk-Request-Priority
    in: header
    type: number
  'trait:includeParameter:include':
    name: include
    in: query
    type: array
    items:
      type: string
  'trait:ticketSorting:sort_by':
    name: sort_by
    in: query
    type: string
  'trait:ticketSorting:sort_order':
    name: sort_order
    in: query
    type: string
definitions:
  channel:
    title: Channel
    type: object
    properties:
      via_type:
        type: string
      via_id:
        type: integer
      '':
        type: string
  ticket:
    title: Ticket
    type: object
    properties:
      id:
        type: string
      external_id:
        type: string
      brand_id:
        type: string
      form_id:
        type: string
      channel:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
          source:
            type: object
      people:
        type: object
        properties:
          requester:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              email:
                type: string
          submitter_id:
            type: string
          assignee_id:
            type: string
          organization_id:
            type: 'null'
          group_id:
            type: string
          collaborators:
            type: object
            properties:
              '456789':
                type: boolean
      topics:
        type: object
        properties:
          source:
            type: 'null'
      tickets:
        type: object
        properties:
          problem:
            type: 'null'
          incidents:
            type: 'null'
      satisfaction:
        type: object
        properties:
          rating:
            type: 'null'
          probability:
            type: 'null'
          comment:
            type: 'null'
      sharing_agreements:
        type: object
        properties:
          '53258401':
            type: boolean
      fields:
        type: object
        properties:
          tags:
            type: object
            properties:
              sample:
                type: boolean
              zendesk:
                type: boolean
          ticket_type:
            type: string
          subject:
            type: object
            properties:
              text:
                type: string
          priority:
            type: string
          status:
            type: string
          recipient:
            type: 'null'
          custom:
            type: object
            properties:
              custom_field_key:
                type: object
                properties:
                  value:
                    type: string
                  type:
                    type: string
                  name:
                    type: string
      metrics:
        type: object
        properties:
          group_stations:
            type: integer
          assignee_stations:
            type: integer
          reopens:
            type: integer
          replies:
            type: integer
          reply_time_in_minutes:
            type: object
            properties:
              calendar:
                type: integer
              business:
                type: integer
          first_resolution_time:
            type: object
            properties:
              calendar:
                type: integer
              business:
                type: integer
          full_resolution_time:
            type: object
            properties:
              calendar:
                type: integer
              business:
                type: integer
          agent_wait_time:
            type: object
            properties:
              calendar:
                type: integer
              business:
                type: integer
          requester_wait_time:
            type: object
            properties:
              calendar:
                type: integer
              business:
                type: integer
          on_hold_time:
            type: object
            properties:
              calendar:
                type: integer
              business:
                type: integer
      dates:
        type: object
        properties:
          created:
            type: string
          updated:
            type: string
          due:
            type: 'null'
          assignee_updated:
            type: string
          requester_updated:
            type: string
          status_updated:
            type: string
          initially_assigned:
            type: string
          assigned:
            type: string
          solved:
            type: string
          latest_comment:
            type: string
      audits:
        type: array
        items:
          type: object
